version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"

  frontend:
    image: nginx:latest
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "8080:80"